-- =============================================================================
-- DEPRECATED
-- =============================================================================
-- File ini sudah tidak digunakan lagi.
--
-- Semua schema SQL sekarang terpusat di folder:
--   db/init.sql          → untuk fresh install / VPS
--   db/migrations/       → untuk perubahan incremental
--   db/supabase/         → SQL yang harus dijalankan di Supabase Dashboard
--
-- Cara menjalankan di VPS / server baru:
--   psql -d family_story -f db/init.sql
--
-- Lihat README.md untuk instruksi lengkap.
-- =============================================================================
